### ISSUE TITLE
Bot Fails to Play Music from Given URL

### ISSUE THREAD

**Issue by ghost-in-the-zsh** [uzox/uzox#20]
Telling the bot to `/play <URL>` ends up playing the wrong thing with *some* links. One of the links I was able to reproduce this with was https://www.youtube.com/watch?v=0tDpoLXD3Js. We've seen this with more than just this, but this one is one example.

**Comment by ghost-in-the-zsh** [comment]
Thanks, but I'm not interested in joining your discord. I'm only interested in the issue getting addressed...

**Comment by Moquent** [comment]
Neither am I interested in helping you with Uzox's bot issues on GitHub. This repository is not for issues related to the bot, it's only for any issues with the source code you're facing while trying to self-host.

**Comment by ghost-in-the-zsh** [comment]
> Neither am I interested in helping you with Uzox's bot issues on GitHub.

This is what repository issue trackers are for, and given this reply, I don't think I'd be inclined to go to a Discord channel for this.

> This repository is not for issues related to the bot, it's only for any issues with the source code you're facing while trying to self-host.

Given this repo says this is "The Official Open Source Repository For Uzox, A Discord Music Bot [...]", and it was the top result, I think any reasonable person would believe it is. If this repo isn't it, then can you help point me in the right direction?

I don't get the impression you're interested in helping much, but if you can at least help me with that, I'll be on my way, and we'll both be happy.

Thanks.

**Comment by Moquent** [comment]
> This is what repository issue trackers are for, and given this reply, I don't think I'd be inclined to go to a Discord channel for this.
The repository issue trackers are for code related issues. I asked you to join the discord server for the discord related issues.
 
> Given this repo says this is "The Official Open Source Repository For Uzox, A Discord Music Bot [...]", and it was the top result, I think any reasonable person would believe it is. If this repo isn't it, then can you help point me in the right direction?
It is the official repository, I'm sorry that I didn't mention a point asking for code related issues on GitHub and discord related issues on Discord, but I did mention it in my first comment which was ignored.

> I don't get the impression you're interested in helping much
As much as I'd be happy to help you, I want to do it in the right place. Check my other issues, everything's code related. Now check the discord, I try to help every single person there if it's a discord issue.

> but if you can at least help me with that, I'll be on my way, and we'll both be happy.
To your problem, the issue is with the client itself; it's not 100% accurate, we don't use YouTube's audio directly so having an exact official stream from YouTube is not possible sometimes, results may vary. If you try searching for the title from YouTube on Deezer or Spotify you may not get the exact track. But in some rare cases the tracks which did not work initially start working later.

**Comment by ghost-in-the-zsh** [comment]
> The repository issue trackers are for code related issues. I asked you to join the discord server for the discord related issues. 

Perhaps I don't see it, but it sounds like a distinction without a difference. To clarify, I wasn't looking for help on how to use the bot in Discord; I was just reporting that the bot, and thus someone's code, is doing something incorrectly.


> It is the official repository, I'm sorry that I didn't mention a point asking for code related issues on GitHub and discord related issues on Discord, but I did mention it in my first comment which was ignored. 

When you said this wasn't the right place, I figured there was a different, and correct, repo to report this issue under. Is that not the case? 

Also, to clarify, when I reported the issue and the response I got was basically having the issue closed and being told to "join discord", I didn't ignore it; I rejected it. (I have my reasons for not wanting to join a discord server for the purposes of support. I'll just say that I've been in a few by now where there's always someone whose mod status goes to their head and I'm not interested in having to deal with that nonsense again.) In hindsight, I've probably wasted my time reporting this in vain.

> As much as I'd be happy to help you, I want to do it in the right place. 

I don't think I see the distinction you're trying to explain here; from my PoV, since it's a bot, all issues are "code related", unless it's user error when using the bot commands incorrectly –which wasn't the case in this report. 

> Check my other issues, everything's code related. 

I don't check closed issues. If an issue is closed, then the reasonable belief is that they were actually addressed –not that they were treated the way this one was. We can agree to disagree on this one. 

> Now check the discord, I try to help every single person there if it's a discord issue. 

Are you suggesting that the client bot not behaving correctly isn't a "code related" issue somehow? Because that'd be an odd thing to say. 

> To your problem, the issue is with the client itself; it's not 100% accurate [...] 

This is why I asked what the right place to report this was. For example, does the client have its own separate repo, and thus, issue tracker? 

If the bot is expected to play the contents of the given URL, then where does the "accuracy" problem come from? For example, when given the URL in my OP, the bot switches and plays content from a different URL it was never given (e.g. a 3 hour long video on white noise is one occurrence, but it looks like a random choice from our PoV). 

> we don't use YouTube's audio directly so having an exact official stream from YouTube is not possible sometimes, results may vary. 

So, if I understand you correctly, you're saying that, while the user may be giving the bot some URL A, the bot may be playing the content from some other URL B and possibly even from a different source (e.g. not YouTube when given a YouTube URL)? Seems like an odd, and more complex(?), way to go about things. 

> If you try searching for the title from YouTube on Deezer or Spotify you may not get the exact track. But in some rare cases the tracks which did not work initially start working later. 

I don't believe the YT tracks I'm trying to play are in those other sources. AFAIK, several of the people who post their tracks do so primarily in YT. 

FWIW, I can download and play the YT tracks just fine with other apps, so I suppose I can just keep doing that and listening to them locally. 

In any case, I can see that this is unlikely to get looked at seriously, much less fixed, due to me reporting this in the wrong place, and it seems my time might be better spent doing something else.

Thank you for your time.

**Comment by Moquent** [comment]
> I didn't ignore it; I rejected it. (I have my reasons for not wanting to join a discord server for the purposes of support. I'll just say that I've been in a few by now where there's always someone whose mod status goes to their head and I'm not interested in having to deal with that nonsense again.)

I'm sorry you felt that way. I'm the only developer and helper on the discord server and I try keep all my replies succinct and respectful due to the fact that even I was a victim of situations similar to that and I know other people go through that too.

> Are you suggesting that the client bot not behaving correctly isn't a "code related" issue somehow? Because that'd be an odd thing to say. 

Yeah, this is not code related per say. Playing YouTube links through other sources is natively not accurate. The most we could do is filter all the results to find the best choice.

> If the bot is expected to play the contents of the given URL, then where does the "accuracy" problem come from? For example, when given the URL in my OP, the bot switches and plays content from a different URL it was never given (e.g. a 3 hour long video on white noise is one occurrence, but it looks like a random choice from our PoV). 

If you search for a YouTube title on a source like deezer, there's no guarantee you'd find the exact track. If we supported YouTube natively then it would've been 100% accurate by just using YouTube audio.

> So, if I understand you correctly, you're saying that, while the user may be giving the bot some URL A, the bot may be playing the content from some other URL B and possibly even from a different source (e.g. not YouTube when given a YouTube URL)? Seems like an odd, and more complex(?), way to go about things. 

Well if you were updated about the current music bot issues you'd be surprised to know how big of a deal even supporting a YouTube link in a bot of this scale is. Making it complex and safe keeps the bot running.

I had to get audited by YouTube and communicate with them for weeks to get approved to use their API and that without audio.

> I don't believe the YT tracks I'm trying to play are in those other sources. AFAIK, several of the people who post their tracks do so primarily in YT. 

Yup, that's the issue here, not being able to play audio from YouTube.

> FWIW, I can download and play the YT tracks just fine with other apps, so I suppose I can just keep doing that and listening to them locally. 

Yes you can. Discord music bots, atleast Uzox, are designed for the purpose of collaborative listening for free. If you have a few tracks that are not available on other sources you could use MP3s to play your tracks through the bot.

> In any case, I can see that this is unlikely to get looked at seriously, much less fixed, due to me reporting this in the wrong place, and it seems my time might be better spent doing something else.

You caught me at the wrong time that day... and before you make another comment about that, my point from the start is that I don't want to discuss about source issues on GitHub as they're not related to issues in my code per say. I sincerely apologise for your time and our misunderstanding. I hope the issue has been resolved 👍
